package com.drools.test.vo;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class AhManualVo implements java.io.Serializable {

	static final long serialVersionUID = 1L;

	@org.kie.api.definition.type.Description("内部产品")
	private java.lang.String innerProductCode;
	@org.kie.api.definition.type.Description("续保标志, 基础代码维护, 0-New 新保；1-Renewal 续保；")
	private java.lang.String renewalInd;
	@org.kie.api.definition.type.Description("年龄，单位天")
	private java.lang.Integer ageDays;
	@org.kie.api.definition.type.Description("年龄，单位月")
	private java.lang.Integer ageMonths;
	@org.kie.api.definition.type.Description("年龄，单位年")
	private java.lang.Integer ageYears;
	@org.kie.api.definition.type.Description("与投保人关系")
	private java.lang.String relationShip;
	@org.kie.api.definition.type.Description("人数")
	private java.lang.Integer noOfInsured;
	@org.kie.api.definition.type.Description("保险期限，单位天")
	private java.lang.Integer coverPeriod;

	@org.kie.api.definition.type.Description("在校学生，可选值： Yes-记名/ No-不记名")
	private java.lang.String fullTimeStudent;

	private int quantity;

	@org.kie.api.definition.type.Label("是否特别允许受保标识")
	private java.lang.String specialAcceptance;

	@org.kie.api.definition.type.Label("申报标识")
	private java.lang.String declarationInd;

	@org.kie.api.definition.type.Label("雇员年龄下限")
	private int minAge;

	@org.kie.api.definition.type.Label("雇员年龄上限")
	private int maxAge;

	@org.kie.api.definition.type.Label("保险期限是否满足一年期/两年期")
	private java.lang.String isProjectCode;

	@org.kie.api.definition.type.Label("规则执行结果")
	private String result;

	public AhManualVo() {
	}

	public java.lang.String getInnerProductCode() {
		return this.innerProductCode;
	}

	public void setInnerProductCode(java.lang.String innerProductCode) {
		this.innerProductCode = innerProductCode;
	}

	public java.lang.String getRenewalInd() {
		return this.renewalInd;
	}

	public void setRenewalInd(java.lang.String renewalInd) {
		this.renewalInd = renewalInd;
	}

	public java.lang.Integer getAgeDays() {
		return this.ageDays;
	}

	public void setAgeDays(java.lang.Integer ageDays) {
		this.ageDays = ageDays;
	}

	public java.lang.Integer getAgeMonths() {
		return this.ageMonths;
	}

	public void setAgeMonths(java.lang.Integer ageMonths) {
		this.ageMonths = ageMonths;
	}

	public java.lang.Integer getAgeYears() {
		return this.ageYears;
	}

	public void setAgeYears(java.lang.Integer ageYears) {
		this.ageYears = ageYears;
	}

	public java.lang.String getRelationShip() {
		return this.relationShip;
	}

	public void setRelationShip(java.lang.String relationShip) {
		this.relationShip = relationShip;
	}

	public java.lang.Integer getNoOfInsured() {
		return this.noOfInsured;
	}

	public void setNoOfInsured(java.lang.Integer noOfInsured) {
		this.noOfInsured = noOfInsured;
	}

	public java.lang.Integer getCoverPeriod() {
		return this.coverPeriod;
	}

	public void setCoverPeriod(java.lang.Integer coverPeriod) {
		this.coverPeriod = coverPeriod;
	}

	public java.lang.String getFullTimeStudent() {
		return this.fullTimeStudent;
	}

	public void setFullTimeStudent(java.lang.String fullTimeStudent) {
		this.fullTimeStudent = fullTimeStudent;
	}

	public int getQuantity() {
		return this.quantity;
	}

	public void setQuantity(int quantity) {
		this.quantity = quantity;
	}

	public java.lang.String getSpecialAcceptance() {
		return this.specialAcceptance;
	}

	public void setSpecialAcceptance(java.lang.String specialAcceptance) {
		this.specialAcceptance = specialAcceptance;
	}

	public java.lang.String getDeclarationInd() {
		return this.declarationInd;
	}

	public void setDeclarationInd(java.lang.String declarationInd) {
		this.declarationInd = declarationInd;
	}

	public int getMinAge() {
		return this.minAge;
	}

	public void setMinAge(int minAge) {
		this.minAge = minAge;
	}

	public int getMaxAge() {
		return this.maxAge;
	}

	public void setMaxAge(int maxAge) {
		this.maxAge = maxAge;
	}

	public java.lang.String getIsProjectCode() {
		return this.isProjectCode;
	}

	public void setIsProjectCode(java.lang.String isProjectCode) {
		this.isProjectCode = isProjectCode;
	}

	public java.lang.String getResult() {
		return this.result;
	}

	public void setResult(java.lang.String result) {
		this.result = result;
	}

	public AhManualVo(java.lang.String innerProductCode,
			java.lang.String renewalInd, java.lang.Integer ageDays,
			java.lang.Integer ageMonths, java.lang.Integer ageYears,
			java.lang.String relationShip, java.lang.Integer noOfInsured,
			java.lang.Integer coverPeriod, java.lang.String fullTimeStudent,
			int quantity, java.lang.String specialAcceptance,
			java.lang.String declarationInd, int minAge, int maxAge,
			java.lang.String isProjectCode, java.lang.String result) {
		this.innerProductCode = innerProductCode;
		this.renewalInd = renewalInd;
		this.ageDays = ageDays;
		this.ageMonths = ageMonths;
		this.ageYears = ageYears;
		this.relationShip = relationShip;
		this.noOfInsured = noOfInsured;
		this.coverPeriod = coverPeriod;
		this.fullTimeStudent = fullTimeStudent;
		this.quantity = quantity;
		this.specialAcceptance = specialAcceptance;
		this.declarationInd = declarationInd;
		this.minAge = minAge;
		this.maxAge = maxAge;
		this.isProjectCode = isProjectCode;
		this.result = result;
	}

}